# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  enum_assist:
    import: "package:enum_assist/builder.dart"
    builder_factories: ["enumAssist"]
    build_extensions: { ".dart": ["ge.dart"] }
    auto_apply: dependents
    build_to: source
