name: enum_assist
version: 0.0.1
description: >-
  Seamlessly generate extension methods and json conversion classes for your enums using enum_assist
repository: https://github.com/mrgnhnt96/enum_assist/enum_assist
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  analyzer: ^2.5.0
  build: ^2.1.1
  build_config: ^1.0.0
  change_case: ^1.0.0+2
  enum_assist_annotation:
    path: ../enum_assist_annotation
  json_annotation: ^4.1.0
  meta: ^1.7.0
  source_gen: ^1.1.1
  source_helper: ^1.3.0

dev_dependencies:
  build_runner: ^2.1.4
  build_test: ^2.1.4
  json_serializable: ^5.0.2
  mocktail: ^0.2.0
  test: ^1.18.2
  very_good_analysis: ^2.3.0

scripts: ../../derry.yaml
