name: enum_assist_annotation
version: 0.1.0
description: >-
  Annotations for the `enum_assist` code-generator.
repository: https://github.com/mrgnhnt96/enum_assist/tree/main/packages/enum_assist_annotation
homepage: https://github.com/mrgnhnt96/enum_assist

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  json_annotation: ^4.1.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.4
  # enum_assist:
  #   path: ../enum_assist
  test: ">=1.17.0 <1.18.0"
  very_good_analysis: ^2.3.0

scripts: ../../derry.yaml
